name: python-workshop
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - cartopy
  - netcdf4
  - pyproj
  - eccodes
  - cython
  - pygrib
  - notebook
  - scipy
  - xarray
